name: Copy emergency branch to production branch

on:
  push:
    branches:
      - emergency

jobs:
  copy-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: emergency

      - name: Merge emergency into production
        run: |
          git config --global user.email "viettran101294@gmail.com"
          git config --global user.name "tienviet10"
          git fetch
          git checkout production
          git merge --no-ff --no-edit --allow-unrelated-histories origin/emergency -s recursive -X theirs
          
      - name: Push to production
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: production
